# vim:ft=kitty

background #232322
foreground #e5e5e5

selection_foreground #232322
selection_background #e5e5e5

# normal
color0 #212121
color1 #b7141f
color2 #457b24
color3 #f6981e
color4 #134eb2
color5 #560088
color6 #0e717c
color7 #efefef

# bright
color8 #424242
color9 #e83b3f
color10 #7aba3a
color11 #ffea2e
color12 #54a4f3
color13 #aa4dbc
color14 #26bbd1
color15 #d9d9d9

# inline
cursor #e83b3f
url_color                 #0e717c

# Tabs
active_tab_background     #232322
active_tab_foreground     #e5e5e5

inactive_tab_background   #424242
inactive_tab_foreground   #efefef

tab_bar_margin_color      #b7141f
tab_bar_background        #b7141f

active_border_color       #b7141f
inactive_border_color     #efefef

