#!/bin/sh
loop=true
while $loop ; do
  for f in /home/me/workspace/*.todo ; do
    i=$(($i + 1))
    echo -e "\e[1;31m+------------------------------------------+\e[0m" >> ~/.cache/todo.cache
    echo -e "\e[36m|\e[0m \e[1;31m[ $i ]\e[0m" >> ~/.cache/todo.cache
    echo -e "\e[36m|$(rg -N --heading --color never --null --line-buffered --after-context 1 'Entry' $f)\e[0m" >> ~/.cache/todo.cache
  done
  loop=false
done
cat ~/.cache/todo.cache
\rm ~/.cache/todo.cache
unset f i loop

