#!/bin/bash

# Moves files to a target directory then switches to that directroy, listing the files within
function mvd () {
	original=$1
	target=$2

	if mv -v $original $target ; then
		if [ -d "$target" ] ; then
			cd "$target" && lsd
		else
			cd "${target%/*}" && lsd
		fi
	fi
}
