#!/usr/bin/env bash
conf_path=$HOME/.config/lf
file=$1
w=$2
h=$3
x=$4
y=$5

get_mime_type() {
  file --dereference --brief --mime-type "${1}"
}

if [[ $(get_mime_type) =~ ^video ]]; then
    # vidthumb is from here:
    # https://raw.githubusercontent.com/duganchen/kitty-pistol-previewer/main/vidthumb
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$(vidthumb "$file")" < /dev/null > /dev/tty
    exit 1
fi

kitty_icat() {
  kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" < /dev/null > /dev/tty
}

image_preview() {
  echo "Resolution:" "$(identify -format "%w×%h\n" "${1}")"
  kitty_icat "${1}"
  exit 1
}

video_preview() {
  thumbnail=$("$conf_path"/lf_kitty_vid_preview "${1}")
  kitty_icat "${thumbnail}"
  exit 1
}

text_preview() {
  bat --color=always --style=numbers,changes --line-range=:"${h}" "${1}" \
      || highlight -O truecolor -s molokai --force -l --line-range=1-"${h}" "${1}" \
      || cat "${1}"
}

case "$file" in
  *.md) glow -s dark "$file";;
  *.tgz|*.tar.gz) tar tzf "$file";;
  *.tar.bz2|*.tbz2) tar tjf "$file";;
  *.tar.txz|*.txz) xz --list "$file";;
  *.tar) tar tf "$file";;
  *.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$file";;
  *.rar) unrar l "$file";;
  *.7z) 7z l "$file";;
  *.[1-8]) man "$file" | col -b ;;
  *.o) nm "$file" | less ;;
  *.torrent) transmission-show "$file";;
  *odt,*.ods,*.odp,*.sxw) odt2txt "$file";;
  *.doc) antiword "$file" ;;
  *.docx) docx2txt.pl "$file" - ;;
  .xls) xls2csv "$file";;
  *.xlsx) xlsx2csv "$file";;
  # *.csv) cat "$file" | sed s/,/\\n/g ;;
  *.csv) sed s/,/\\n/g "$file";;
  *.pdf) pdftotext -l 10 -nopgbrk -q "$file" -;;
  *.bmp|*.jpg|*.jpeg|*.png|*.xpm|*.svg|*.gif|*.webp) image_preview "$file";;
  *.wav|*.mp3|*.m4a|*.wma|*.ape|*.ac3|*.og[agx]|*.spx|*.opus|*.as[fx]|*.flac) mediainfo "$file";;
  *.avi|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.mts|*.m4v|*.r[am]|*.qt|*.divx)
    video_preview "$file" || mediainfo "$file";;
  *.ts) [[ $(get_mime_type "$file") == text/* ]] && text_preview "$file" || kitty_icat "$("$conf_path"/vidthumb "$file")" || mediainfo "$file";;
  *.json) jq --color-output . "$file" || bat --color=always --style=numbers,changes --line-range=:"$3" "$file";;
  *) pistol "$file";;
esac
