# set -Ux GDK_BACKEND wayland
set -gx GTK_CSD 1
set -gx MOZ_ENABLE_WAYLAND 1
set -gx MOZ_USE_XINPUT2 1
# qt
set -gx QT_QPA_PLATFORMTHEME qt5ct
set -gx QT_QPA_PLATFORM wayland-egl
set -gx QT_WAYLAND_DISABLE_WINDOWDECORATION 0
