#!/bin/bash

pup () 
{
  check ()
  {
    printf '\e[33mContinue?\e[0m (Y/n)\n'
    read -r -k1 -s response
    if [[ $response == [Nn]* ]]; then
      sleep 1
      printf '\e[31mNo upgrades were made'; sleep 1; printf '.'; sleep 1; printf '.'; sleep 1; printf '.\e[0m\n'
      sleep 1
      exit 1
    else
      sleep 1
      printf '\e[32mUpgrading!\e[0m\n'
      sleep 1
      return 0
    fi
  }

  sum=$(( $(paru -Syyupq | wc -l) - 4 ))

  if [[ $sum -gt 1 ]]; then
    printf '\e[32mI am about to upgrade these packages: \n'
    printf '\e[0m\n'
    paru -Qu
    check
    sleep 2
    ( sudo pacman -Syyu && paru -Syyu --aur && printf '\e[32mSuccess!\n\e[0m' ) || printf '\e[31mUpgrade failed\n\e[0m' 
  else
    printf '\e[33mNo files to upgrade!\n\e[0m'
    sleep 2
  fi
}
