#!/bin/bash

source "$XDG_CONFIG_DIR"/river/layout

riverctl send-layout-cmd kile "outer_padding 6"
riverctl send-layout-cmd kile "view_padding 6"
riverctl focus-output next
riverctl attach-mode bottom
riverctl send-layout-cmd kile "all ${DECK}"
