#!/bin/sh

lg() {
    export LAZYGIT_NEW_DIR_FILE=~/.lazygit/newdir

    lazygit "$@"

    if [ -f $LAZYGIT_NEW_DIR_FILE ]; then
            builtin cd "$(cat $LAZYGIT_NEW_DIR_FILE)" || retun 0
            rm -f $LAZYGIT_NEW_DIR_FILE > /dev/null
    fi
}
